version: '3.8'

services:
  app-api:
    container_name: app-api
    image: media-sharing-platform-api:1.0
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgrespw@postgresDB:5432
      - DB_AUTO_MIGRATE=true
      - AUTH_HMAC_SECRET=topsecretkey
      - AUTH_EXPIRATION_MINUTES=10080 #7 days
      - MAX_MULTIPART_MEMORY=20971520 #20 MiB
      - SUPPORTED_FILE_EXTENSIONS=.png|.jpg|.jpeg|.mp4
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - app_network
    ports:
      - 3000:3000
    depends_on:
      - postgresDB

  postgresDB:
    container_name: postgresDB
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgresDB
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge